### ISSUE TITLE
Add section for setting up a Rails environment for Mac OS X

### ISSUE THREAD

**Issue by hortongn** [uclibs/Developer_Guides#1]
We need a step-by-step guide that someone can use to prepare a Mac for Rails development.

The basics:
1. Install XCode from the App store
2. Install RVM: `\curl -sSL https://get.rvm.io | bash -s stable`
3. Install Homebrew: `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
4. Install some needs utilities: `brew install git redis graphicsmagick`
5. Install a ruby 2.1.x: `rvm 2.1.6 --install --default`

**Comment by jayanthdeejay** [comment]
http://installrails.com/
